### PR TITLE
add Terminal.get_location() method

### PR DESCRIPTION
**Pull request by jquast**
This PR succeeds #32 by @thomasballinger.

major
--------
- **new method**, ``.get_location(timeout=None)``.
- **new method**, ``.ungetch()`` which pushes data back for next ``inkey()``.
- **new example** program, ``bin/resize.py``, which required such condition.
- **new example** program, ``bin/detect-multibyte.py`` which uses this method.
- enhancement: now possible to use stdin when stream=stderr

minor
--------
- method-local function, ``time_left()``, moved to ``keyboard.py`` as ``_time_left()``.
- new function in keyboard.py, ``_read_until``, something like a mini-pexpect.
- new private state value ``_line_buffered``, used to determine whether the terminal has already entered cbreak or raw mode. This may become public later if we also use termios routines, instead as a read-only \@property.

### CODE REVIEW

**Comment by jquast** [comment]
This pull request is completed and ready for review, I plan to release within 8 hours. Review now or forever hold your peace, this is an API, it sticks!

**Comment by jquast** [comment]
merged by squash in e9ad7b85dfcbbba49010ab8c13e3a5920d81b010

**Comment by thomasballinger** [comment]
Piece forever held, except to say this looks good. A few questions for my own learning:

* Why not return a namedtuple from `get_location` if it was useful enough to create in both scripts?
* Not changed in diff, but what isn't optimal about escape key handling at https://github.com/jquast/blessed/commit/e9ad7b85dfcbbba49010ab8c13e3a5920d81b010#diff-38e8ce39d6855e67e35e8ce425d43350L961

**Comment by jquast** [comment]
> Why not return a namedtuple from get_location if it was useful enough to create in both scripts?

good suggestion, maybe we should.

> Not changed in diff, but what isn't optimal about ..

to hint at terminals like "avatar" or "kermit" type, where sequences do not begin with escape, and all of this given input logic will fail on its face, it gets really weird, the abstraction doesn't apply and maybe even disrupts? Luckily these (what I call "binary packed" terminals) are so uncommon that I've made it into a list of terminals that emits a warning when used, we focus mostly on software emulated terminals.

 I can try to better squeeze these details into the comment block if you suggest

**Pull request closed without merging**
