### PR TITLE
Fixes so tests will pass

### PR DESCRIPTION
**Pull request by avylove**
I was working on a different pull request and realized all the test were failing. There were a number of reasons, all pretty simple.
- Needed to remove a travis-ci workaround
- Minor changes to libraries (pytest, pytest-cov, sphinx)
  - I removed "coverage combine" in tox because it was failing and looks like it's not necessary anymore
- Depreciated modules (imp)
- Formatting changes for stricter linting

I also bumped the versions so 3.7 is used for about, sa, and sphinx. Also included 3.8-dev in travis

Might be worth configuring travis to run periodically. Most of my projects are configured to run the tests once a week. I get an email a couple times a year when something fails. Usually because of linting or a minor API change. Easier to deal with them as they come up than all at once.

### CODE REVIEW

**Comment by avylove** [comment]
Have you had a chance to take a look?

**Comment by jquast** [comment]
I’ll try to merge it by Monday, bear with my busy schedule thanks !!

**Comment by avylove** [comment]
No worries, I get it.

**Comment by jquast** [comment]
Thanks again for your contribution, best wishes

**Pull request merged**
