### PR TITLE
Fixes and non-critical testing for Python 3.10-dev

### PR DESCRIPTION
**Pull request by avylove**
Travis added support for testing early releases of Python 3.10. Everything works except the version test in `__init__.py`, which needs to use integers instead of strings in order to support comparison of two digit version elements.

### CODE REVIEW

**Comment by avylove** [comment]
The main reason for a release is to support downstream testing of 3.10, which is how I found the bug. What do they say about testing? Early and often.

I agree, that code can probably be deleted. There are no downloads for 3.2 and even very few for 3.3. Here are the stats for the last month.

| python_version | download_count |
| -------------- | -------------- |
| 3.6            |         95,327 |
| 2.7            |         73,348 |
| 3.7            |         52,873 |
| 3.8            |         52,243 |
| 3.5            |         12,527 |
| 3.4            |          1,111 |
| 3.9            |             90 |
| 3.3            |             48 |
| 2.6            |              8 |
| 3.10           |              3 |
| Total          |        287,578 |

**Comment by avylove** [comment]
Actually, if we do that, we should probably drop 3.2 from the supported versions, but while the net effect is probably nil, that shouldn't be done in a bug release. So I'm thinking just fix it for now and drop 3.2 the next time there's a feature release.

**Comment by avylove** [comment]
Sorry for the extra commits in master. I think github had a hiccup. I did a squash and merge, but it told me it failed. Then I saw it did a merge without the squash

**Comment by jquast** [comment]
No problem—best wishes

**Pull request merged**
