### PR TITLE
inkey returns immediately with invalid MBS prefix input

### LINKED ISSUE #30: Disregard esc_delay in inkey if sequence is not a prefix of any known sequences
To make `inkey()` not delay on "meta-sends-escape" keypresses, would be nice to check if Escape plus the characters after it could possibly resolve to something and not delay if there is no possible "partial resolution" of these characters. I did this in Curtsies by building a prefix table. In a comment at https://github.com/jquast/blessed/blob/master/blessed/terminal.py#L740 it says ` \x1b[`,`\x1bO`, and `\x1b?` are the three to worry about - if there's a character following esc and it's not one of these three could inkey return immediately?

### PR DESCRIPTION
**Pull request by thomasballinger**
Fixes #30

### CODE REVIEW

**Comment by jquast** [comment]
just popping in to say I'll probably dust this off soon in hopes to include it upstream in a merge with blessings

**Comment by thomasballinger** [comment]
That's exciting! I could work on this or the some on Wednesday, or could take some subsection if that's helpful.

**Comment by jquast** [comment]
Coming back to tell you, spent all time since January trying to merge upstream to blessings project. Failed, merging the improvements done in rejected upstream back downstream, and blessed progress can finally continue. I will be merging this maybe even today.

**Comment by thomasballinger** [comment]
Terrific, I'm excited this is happening. If I give my terminal talk again I'll be sure to plug Blessed for these extra features instead of the "any month now" message I had been sharing about Blessed getting into Blessings.

I won't say I'll work on this soon because I kept failing at that, but I might soon!

**Comment by jquast** [comment]
Awesome, you're in NYC aren't you? I plan to do a talk in CA regarding terminals soon. Anyway, project is resuming finally :)

**Comment by jquast** [comment]
This PR continues as #31 (git conflicts, bring branch upstream and merge w/master). Also @thomasballinger you have been added collaborator to this repository.

**Comment by thomasballinger** [comment]
Thanks for the commit bit, and let me know when you give that talk!

**Pull request closed without merging**
