### PR TITLE
Add 'Typing :: Typed' classifier

### PR DESCRIPTION
**Pull request by dlax**
Follow-up on #190, see https://pypi.org/classifiers/.

### CODE REVIEW

**Review by jquast — APPROVED** [review]

**Comment by jquast** [comment]
Thank you, this will be in next release shortly

**Comment by dlax** [comment]
The PR is closed but it's not merged; was that intentional?

**Comment by jquast** [comment]
thanks ill try to release with next update this weekend

**Comment by jquast** [comment]
sorry, i've been busy .. soon

**Pull request merged**
