### PR TITLE
[compat] Remove support for deprecated python version

### PR DESCRIPTION
**Pull request by Djailla**
This allows :
- code cleanup
- remove six dependency

### CODE REVIEW

**Comment by avylove** [comment]
I don't think this is a good idea. By Python version, 2.7 is the second most downloaded version with almost 82,000 downloads in the last month. It would also have downstream effects. Unless it becomes a blocker for new functionality, I'm not sure it makes sense now.

**Comment by Djailla** [comment]
@avylove ok, it's just python 2.7 is now deprecated and removing support will push users to migrate.

By the way, what is the first python version downloaded and from where do you get these number s ?

**Comment by jquast** [comment]
Agree.I’ve worked at several businesses that cannot upgrade Linux or Python long beyond its years. I have personally downgraded a dozen or more python packages to earlier python releases as required by employers.

If just one person has to backport blessed to python 2, the cost to that person is greater than our cost to support it at this time. Maybe when we add asyncio support or something I might change my mind.

**Comment by Djailla** [comment]
@jquast agree with who ? ;)

No problem to keep my PR on hold for a (long) while, it was worth the effort and I learned few stuff.

About the migration effort, based on the list of project displayed here, this was my motivation to remove support of good old python 2 : https://python3statement.org

**Comment by avylove** [comment]
@Djailla, the largest number of downloads are for Python 3.6. I use [pypinfo](https://pypi.org/project/pypinfo/) to get those numbers.

I understand the desire to move to Python 3, but pushing users isn't the right way to go about it. It seems to me the people behind these efforts are disconnected from how things play out in the real world. Most of the work I've done has been in large enterprise environments. In those environments RHEL/CentOS is by far the most prevalent OS. It takes a long time time both to put out a new version of an enterprise baseline and a long time to move people off of them. RHEL 8 has been out for a year and I know many places where people are still struggling to get off RHEL 6 which will be EOL this November. RHEL 6 was released in 2010. Certainly a dinosaur in Linux terms, but still very much in use. And it shipped with Python 2.6!

So what you find right now is RHEL/CentOS 7 is one of the most widely installed distros, and it shipped with Python 2.7. Python 3.6 is available through EPEL, but not as many RPMs are available for Python packages for 3.6. Why is that important? Because in many of these environments everything has to be installed through RPMs for security and auditing purposes. What happens when you maintain these baselines is you end up backporting a lot of packages, because it's the path of least resistance. By deprecating Python versions without a good reason, you just make it harder for people doing this work.

The same holds for other LTS distros and large legacy application code bases.

For my part, I contribute to EPEL and try to make sure all the packages I maintain are available for Python 3. Sometimes that's relatively easy, but sometimes it requires packaging a bunch of dependencies. As for Python 2, I think of June 30, 2024 (EOL for RHEL 7) as a more accurate date for the death of Python 2. I have no doubt it will be still be in use somewhere, but the numbers should be pretty small by then.

**Comment by Djailla** [comment]
Hello @avylove 

I totally agree with your statement. In Criteo (the big company where I work) we use CentOS 7 and are limited to python 3.6

I'm a little more optimistic about the decline of python 2.7 before 2024.

So, your call, either you keep my PR open for a later merge or I can close it. But I would ague this would be a friendly reminder :p

**Comment by Djailla** [comment]
Hello @avylove any update on my previous message ?

**Comment by avylove** [comment]
By the time we're ready to pull Python 2 support, the code will have changed to the point that it would be easier to do another PR. As far as a reminder. I think that will come when either the tests break or we want to implement a breaking change. Your efforts are definitely appreciated. If you have other PRs, please send them.

**Comment by jquast** [comment]
We are dropping python 2.6, #196

**Pull request closed without merging**
