### PR TITLE
Update terminal.py

### PR DESCRIPTION
**Pull request by mwchase**
Attempt to make pylint happy with the kwargs documentation.

This line broke my other PR, so if this passes, it should be good.

### CODE REVIEW

**Comment by avylove** [comment]
I think pydocstyle wants to start the docstring with r""" if it has backslashes.
Looking at the documentation produced, Sphinx wants a single backslash.
I think there is a bug in Pylint that isn't removing the escapes before comparing the strings. Worth reaching out to them with an issue to see if it's a quick fix. If not, we may just need to ignore this error.

**Comment by mwchase** [comment]
Just confirmed locally that Sphinx does not like having the backslash removed. I investigated on the pylint side, and it looks like this is https://github.com/PyCQA/pylint/issues/5406.

Thinking about what to do in terms of getting things to pass, my inclination would be to revert the changes to the docstring, and either version-lock pylint below `2.12`, or add inline disables to the function definition, though I'm happy to do whatever. Any preferences?

**Comment by avylove** [comment]
I don't think we're in a hurry. Let's see what the Pylint guys say. They tend to fix things like this pretty quickly. If it becomes a blocker we'll just inline disable that check, but we can hold off for now.

**Comment by mwchase** [comment]
I just confirmed that the new pylint release passes accepts these changes, so this should be good to try again whenever.

**Review by avylove — APPROVED** [review]
Looks good to me

**Pull request merged**
