### PR TITLE
Fixing https://github.com/jquast/blessed/issues/84

### PR DESCRIPTION
**Pull request by croepha**

### CODE REVIEW

**Comment by croepha** [comment]
Im looking into those checks right now

**Comment by croepha** [comment]
I really don't know how to fix the travis issue, my tox tests passed

**Comment by jquast** [comment]
The linter versions are not pinned, so you are failing static analysis that passed just weeks ago. Exciting stuff :)  Anyway I'll merge, augment, and release -- Thanks dave!

**Comment by croepha** [comment]
No problem! :)

**Pull request merged**
