### PR TITLE
Typing

### LINKED ISSUE #190: type hints?
It'd be nice to add type hints [PEP 484](https://www.python.org/dev/peps/pep-0484/) in blessed code base and then distribute them (following [PEP 561](https://www.python.org/dev/peps/pep-0561/)).

Is there any interest in this? (or any objection)

Since the library still supports Python 2, we'll need to write type annotations as stub files (`.pyi`).

I'd be happy to start working on this.

### PR DESCRIPTION
**Pull request by dlax**
This adds type annotations and declares the packages as "typed" as proposed in #190. Only the public API is typed.

Typing is checked with mypy in strict mode as far as the blessed/ directory is concerned. Checks are added in tox and travis-ci.

Last commits contain small changes to help type checking in the tests suite.

Running `mypy  --check-untyped-defs tests/` report some type "errors", most of which are not real errors (e.g. access to a private/untyped attribute or missing assertions).

Fix #190.

### CODE REVIEW

**Comment by avylove** [comment]
Not sure we need a mypy.ini when those statements can go in setup.cfg

**Comment by jquast** [comment]
Excellent work, thank you.

**Comment by dlax** [comment]
> Not sure we need a mypy.ini when those statements can go in setup.cfg

That'd be fine as well. So, do you want this to be changed?

**Comment by avylove** [comment]
> > Not sure we need a mypy.ini when those statements can go in setup.cfg

> That'd be fine as well. So, do you want this to be changed?

That's my preference to reduce the number of files in the root, but @jquast may feel differently.

Unrelated, it looks like the error with 3.10 will be fixed in the next release of six.

**Review by jquast — APPROVED** [review]

**Comment by jquast** [comment]
I've moved it to setup.cfg it will be in next release, thank you again

**Pull request merged**
